version: '3.8'

services:
  web:
    build:
      context: ../../../apps/web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../../../apps/web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - gateway

  gateway:
    build:
      context: ../../../services/gateway
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ../../../services/gateway:/app
    environment:
      - GO_ENV=development
    depends_on:
      - postgres
      - redis

  compute:
    build:
      context: ../../../services/compute
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    volumes:
      - ../../../services/compute:/app
    environment:
      - RUST_ENV=development

  realtime:
    build:
      context: ../../../services/realtime
      dockerfile: Dockerfile.dev
    ports:
      - "8082:8082"
    volumes:
      - ../../../services/realtime:/app
    environment:
      - MIX_ENV=dev

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=zephyr
      - POSTGRES_PASSWORD=zephyrdev
      - POSTGRES_DB=zephyr_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
