version: '3.8'

services:
  gateway:
    build: 
      context: ./services/gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://zephyr:zephyrdev@postgres:5432/zephyr
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  compute:
    build:
      context: ./services/compute
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://zephyr:zephyrdev@postgres:5432/zephyr

  realtime:
    build:
      context: ./services/realtime
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgres://zephyr:zephyrdev@postgres:5432/zephyr
      - REDIS_URL=redis://redis:6379

  cache:
    build:
      context: ./services/cache
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: zephyr
      POSTGRES_PASSWORD: zephyrdev
      POSTGRES_DB: zephyr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
