version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - web
    networks:
      - zephyr_network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    networks:
      - zephyr_network

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: zephyr
      POSTGRES_PASSWORD: zephyrdev
      POSTGRES_DB: zephyr
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zephyr_network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - zephyr_network

networks:
  zephyr_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  nginx_logs:
