repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
  
  # The name of the repository. Changing this will rename the repository
  name: zephyr-v2
  
  # A short description of the repository that will show up on GitHub
  description: An advanced educational platform with AI-powered learning assistance
  
  # Either `true` to make the repository private, or `false` to make it public.
  private: false
  
  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true
  
  # Either `true` to enable projects for this repository, or `false` to disable them.
  has_projects: true
  
  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: true

  # Updates the default branch for this repository.
  default_branch: main

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        contexts: ['test', 'lint', 'build']
      enforce_admins: false
      restrictions: null
