version: '3.8'

services:
  web:
    image: zephyr/web:${TAG:-latest}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
    depends_on:
      - gateway

  gateway:
    image: zephyr/gateway:${TAG:-latest}
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
    deploy:
      replicas: 3
    depends_on:
      - postgres
      - redis

  compute:
    image: zephyr/compute:${TAG:-latest}
    ports:
      - "8081:8081"
    environment:
      - RUST_ENV=production
    deploy:
      replicas: 2

  realtime:
    image: zephyr/realtime:${TAG:-latest}
    ports:
      - "8082:8082"
    environment:
      - MIX_ENV=prod
    deploy:
      replicas: 2

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=zephyr_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
